name: Deploy Website2
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Ensure submodules are pulled if needed

      - name: Debug files
        run: ls -R  # Check repo structure to verify package.json exists

      - name: Install dependencies
        run: npm ci
        working-directory: my-app  # Change if package.json is inside a subfolder

      - name: Lint code
        run: npm run lint
        working-directory: my-app  # Change if needed

      - name: Test code
        run: npm run test
        working-directory: my-app  # Change if needed

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: npm ci
        working-directory: my-app  # Ensure correct working directory

      - name: Build website
        run: npm run build
        working-directory: my-app  # Ensure correct working directory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
