name: Deploy Website
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: '03 Finished Project'  # Checks out repo into this subdirectory

      - name: Verify files
        run: |
          ls -la "03 Finished Project/"
          ls -la "03 Finished Project/src"  # Debug paths

      - name: Install dependencies
        working-directory: "03 Finished Project"  # All npm commands run here
        run: npm ci

      - name: Lint code
        working-directory: "03 Finished Project"
        run: npm run lint

      - name: Test code
        working-directory: "03 Finished Project"
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: '03 Finished Project'

      - name: Install dependencies
        working-directory: "03 Finished Project"
        run: npm ci

      - name: Build website
        working-directory: "03 Finished Project"
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        working-directory: "03 Finished Project"
        run: echo "Deploying from 03 Finished Project directory"
