name: Events Demo 

on:
  pull_request:
    types:
      - opened
    branches:
      - main # main
      - dev-* # dev-new dev-this-is-new
      - feat/** # feat/new feat/new/button

  push:
    branches:
      - main # main
      - dev-* # dev-new dev-this-is-new
      - feat/** # feat/new feat/new/button
      - developer-1
    paths-ignore:
      - .github/workflows/*

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      
      - name: Get code
        uses: actions/checkout@v3

      - name: Verify working directory
        run: |
          echo "Current working directory: $(pwd)"
          echo "Files in the directory:"
          ls -la

      - name: Ensure package.json exists
        run: |
          if [ ! -f package.json ]; then
            echo "Error: package.json not found! Check repository structure."
            exit 1
          fi

      - name: Install dependencies
        run: npm ci || npm install

      - name: Test code
        run: npm run test

      - name: Build code
        run: npm run build

      - name: Deploy project
        run: echo "Deploying..."

