name: Events Demo 

on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - dev-* 
      - feat/** 

  push:
    branches:
      - main
      - dev-* 
      - feat/** 
      - developer-1
    paths-ignore:
      - .github/workflows/*

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify repository structure
        run: |
          echo "Checking repository structure..."
          echo "Current directory: $(pwd)"
          echo "Listing files:"
          ls -la

      - name: Change to project directory
        run: |
          cd "03 Finished Project"
          echo "Switched to project directory: $(pwd)"
          ls -la

      - name: Check if package.json exists
        run: |
          if [ ! -f "03 Finished Project/package.json" ]; then
            echo "Error: package.json not found in '03 Finished Project'!"
            exit 1
          fi

      - name: Install dependencies
        run: |
          cd "03 Finished Project"
          echo "Checking for package-lock.json..."
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json not found. Running npm install to generate it."
            npm install
          else
            npm ci
          fi

      - name: Run tests
        run: |
          cd "03 Finished Project"
          npm test

      - name: Build project
        run: |
          cd "03 Finished Project"
          npm run build

      - name: Deploy project
        run: |
          cd "03 Finished Project"
          echo "Deploying..."
